kuzzleio/kuzzle-device-manager

lib/DeviceManagerPlugin.ts, lib/core-classes/DecodersService.ts
=> move logic of registerDecoder inside the decodersController & service

lib/DeviceManagerPlugin.ts, lib/core-classes/DeviceManagerEngine.ts, package-lock.json, package.json
Use the packaged and fixed version of `kuzzle-plugin-commons` to avoid unwanted breaking changes
=> Use packaged kuzzle plugin commons

lib/core-classes/BatchProcessing/BatchController.ts, package-lock.json, package.json
Original PR: https://github.com/kuzzleio/kuzzle-device-manager/pull/147
=> Fix batch writter errors

features/DeviceController.feature, lib/core-classes/DeviceService.ts, package-lock.json, package.json
- [ [#164](https://github.com/kuzzleio/kuzzle-device-manager/pull/164) ] Remove measure when unlinking asset   ([Aschen](https://github.com/Aschen))
---
=> Release 0.4.14

lib/DeviceManagerPlugin.ts, lib/core-classes/PayloadService.ts, package-lock.json, package.json
=> add capacities to override some method of the plugin

lib/DeviceManagerPlugin.ts, lib/core-classes/PayloadService.ts, package-lock.json, package.json
- [ [#176](https://github.com/kuzzleio/kuzzle-device-manager/pull/176) ] Add capacities to override some method of the plugin   ([TisserantG](https://github.com/TisserantG))
---
=> Release 0.4.15

lib/controllers/AssetController.ts, lib/core-classes/DeviceService.ts, lib/core-classes/PayloadService.ts, lib/models/BaseAsset.ts, lib/models/Device.ts
Ensure Devices and Assets always have an array for the `measures` property
=> Ensure measures is always iterable for Device and Asset

lib/controllers/AssetController.ts, lib/core-classes/DeviceService.ts, lib/core-classes/PayloadService.ts, lib/models/BaseAsset.ts, lib/models/Device.ts
Reverts kuzzleio/kuzzle-device-manager#178 because of wrong target branch
=> Revert "Ensure measures is always iterable for Device and Asset"

doc/2/controllers/asset/get/index.md, doc/2/guides/Asset Category/index.md, doc/2/guides/Metadata/index.md, doc/2/guides/asset-category/index.md, doc/2/guides/metadata/index.md, doc/2/index.md, features/AssetCategory.feature, lib/controllers/AssetCategoryController.ts, lib/controllers/AssetController.ts, lib/controllers/RelationalController.ts
give a genericGet function in the genericController that resolve all nested link and give processed object with all id key of nested link replanced by the object in ES. Like all function in genericController, the mecanism is recursive.
You can create objects with nested link, and do get on them, or play with functional test.
add documentation.
=> genericGet and updateDoc

features/AssetController.feature, lib/controllers/AssetController.ts, package-lock.json, package.json
hotfix : link an asset with metadata to an assetcategory result previously to an error. 
Hotfix resolve the problem.
=> hotfix : link an asset with metadata to an assetcategory

features/PayloadController.feature, features/fixtures/application/app.ts, features/fixtures/application/decoders/DummyAccelerometer3d.ts, features/fixtures/application/decoders/DummyTempDecoder.ts, features/fixtures/application/decoders/index.ts, features/fixtures/application/measures/Acceleration3dMeasure.ts, lib/DeviceManagerPlugin.ts, lib/core-classes/MeasureService.ts, lib/models/Device.ts, lib/types/DecodedPayload.ts, package-lock.json, package.json
This PR add the `DecodedPayload.addMetadata` method to allows Decoder to extract Device metadata from incoming payloads
=> Allow decode Device metadata

features/fixtures/application/decoders/DummyTempDecoder.ts, features/fixtures/application/decoders/DummyTempPositionDecoder.ts, index.ts, lib/core/DeviceManagerPlugin.ts, lib/core/registers/ModelsRegister.ts, lib/modules/decoder/Decoder.ts, lib/modules/measure/measures/BatteryMeasure.ts, lib/modules/measure/measures/HumidityMeasure.ts, lib/modules/measure/measures/MovementMeasure.ts, lib/modules/measure/measures/PositionMeasure.ts, lib/modules/measure/measures/TemperatureMeasure.ts, lib/modules/model/types/ModelDefinition.ts, package-lock.json, package.json
Expose `DeviceModelDefinition` and `AssetModelDefinition`
=> Export DeviceModelDefinition and AssetModelDefinition

.github/workflows/codeql.workflow.yml, benchmark/benchmark.js, features/fixtures/application/assets/Container.ts
Add Github CodeQL (formerly LGTM)
=> Add CodeQL

lib/modules/shared/types/DigitalTwinContent.ts, lib/modules/shared/types/Metadata.ts, package-lock.json, package.json
Allows `null` for each measure of a `DigitalTwin` as well as metadata values.
=> Add nullable types

lib/core/DeviceManagerEngine.ts, lib/modules/model/ModelService.ts, package-lock.json, package.json
Allows to declare more than 100 models for measures, assets and devices
=> Allows more than 100 measure models

features/fixtures/application/assets/Container.ts, features/fixtures/application/tests/pipes.ts, lib/core/DeviceManagerPlugin.ts, lib/modules/measure/MeasureService.ts, lib/modules/shared/index.ts, lib/modules/shared/utils/keepStack.ts, tests/helpers/payloads.ts, tests/modules/ingestion-pipeline/before-ingestion.test.ts
Ensure we can add new computed measure in the ingestion pipeline and save them into the asset.
- keep errors original stack
=> Fix adding of computed mesure in ingestion pipeline

features/fixtures/application/assets/Container.ts, features/fixtures/application/tests/pipes.ts, features/fixtures/fixtures.js, lib/core/DeviceManagerPlugin.ts, lib/modules/asset/types/AssetApi.ts, lib/modules/decoder/PayloadService.ts, lib/modules/device/DeviceService.ts, lib/modules/device/types/DeviceContent.ts, lib/modules/measure/MeasureService.ts, lib/modules/measure/types/MeasureContent.ts, lib/modules/shared/index.ts, lib/modules/shared/utils/keepStack.ts, lib/modules/shared/utils/objectDiff.ts, package-lock.json, package.json, tests/helpers/index.ts, tests/helpers/payloads.ts, tests/modules/assets/asset-history.test.ts, tests/modules/ingestion-pipeline/before-ingestion.test.ts
- [ [#269](https://github.com/kuzzleio/kuzzle-device-manager/pull/269) ] Add lang search parameter in ApiAssetSearchRequest type   ([tdislay](https://github.com/tdislay))
- [ [#268](https://github.com/kuzzleio/kuzzle-device-manager/pull/268) ] Fix adding of computed mesure in ingestion pipeline   ([Aschen](https://github.com/Aschen))
- [ [#266](https://github.com/kuzzleio/kuzzle-device-manager/pull/266) ] Fix type of assetId and engineId   ([Aschen](https://github.com/Aschen))
- [ [#267](https://github.com/kuzzleio/kuzzle-device-manager/pull/267) ] Support nested metadata diff for asset history   ([Aschen](https://github.com/Aschen))
---
=> Release 2.1.2

lib/modules/device/DevicesController.ts, tests/modules/devices/link-unlink-asset.test.ts
Prevent to link a device to an asset without providing any measure
=> Prevent empty link

lib/modules/asset/roles/RoleAssetsAdmin.ts, lib/modules/asset/roles/RoleAssetsReader.ts, lib/modules/device/roles/RoleDevicesAdmin.ts, lib/modules/device/roles/RoleDevicesReader.ts
Fix the actions defined in the roles to work with IoT Console v3
=> Fix roles for IoT console v3

doc/2/controllers/devices/linkAsset/index.md, lib/modules/device/DeviceService.ts, tests/helpers/document.ts, tests/scenario/modules/devices/action-link-asset.test.ts
This PR allows to update a device link without having to unlink the device first.
=> Allows to replace the device link with new measures

lib/modules/asset/AssetService.ts, package-lock.json, package.json
=> Fix search result type in AssetService

lib/modules/measure/MeasureService.ts, package-lock.json, package.json
Measures can be uninitialized.
=> Handle uninitialized measure in historization

lib/modules/asset/types/AssetEvents.ts, package-lock.json, package.json
=> 2.2.3: fix AssetEvent import

package-lock.json, package.json
- [ [#302](https://github.com/kuzzleio/kuzzle-device-manager/pull/302) ] fix: CSV column headers and path to values should not be the same ([tdislay](https://github.com/tdislay))
=> Release 2.2.6

lib/modules/measure/MeasureExporter.ts, package-lock.json, package.json, tests/scenario/modules/assets/action-export-measures.test.ts, tests/scenario/modules/devices/action-export-measures.test.ts
- [ [#304](https://github.com/kuzzleio/kuzzle-device-manager/pull/304) ] Fix(csv export): asset with measures of the same type but different names   ([tdislay](https://github.com/tdislay))
---
=> Release 2.2.7

doc/2/concepts/models/index.md, doc/2/controllers/models/write-asset/index.md, doc/2/controllers/models/write-device/index.md, lib/modules/model/ModelService.ts, lib/modules/model/ModelsController.ts, lib/modules/model/ModelsRegister.ts, lib/modules/model/collections/modelsMappings.ts, lib/modules/model/types/ModelContent.ts, lib/modules/model/types/ModelDefinition.ts, lib/modules/plugin/DeviceManagerPlugin.ts, tests/application/assets/Container.ts, tests/application/assets/Warehouse.ts, tests/hooks/collections.ts, tests/scenario/migrated/model-controller.test.ts
- Implement comprehensible metadatas (optional)
- Implement groups for metadatas (optional)
- Implement corresponding test
- Documentation
- Improve code documentation
- improve types
=> feat: implement comprehensible metadata

lib/modules/model/types/ModelApi.ts
related to [https://github.com/kuzzleio/kuzzle-device-manager/pull/332](PR) .
- implement missing api types
=> fix: correct api types

lib/modules/model/ModelService.ts, tests/scenario/migrated/model-controller.test.ts
- [Exposes](https://github.com/kuzzleio/kuzzle-device-manager/actions/runs/9345460608) and fix a bug were listAssets would not return commons templates on a given engine
- create a engine : commons model
- try to list on an engine
- it should now return commons templates
- added a test
=> fix(models):  list asset returns commons assets

lib/modules/measure/MeasureExporter.ts, lib/modules/shared/services/AbstractExporter.ts, lib/modules/shared/services/DigitalTwinExporter.ts, tests/scenario/modules/assets/action-export-measures.test.ts, tests/scenario/modules/assets/action-export.test.ts, tests/scenario/modules/devices/action-export-measures.test.ts, tests/scenario/modules/devices/action-export.test.ts
WIP
- Step 1 :
- Step 2 :
- Step 3 :
KZLPRD-330
=> feat: add UTC export by default for devices and assets

doc/2/controllers/assets/upsert/index.md, doc/2/controllers/devices/upsert/index.md, lib/modules/device/DeviceService.ts, lib/modules/device/DevicesController.ts, lib/modules/device/types/DeviceApi.ts, tests/scenario/migrated/device-upsert.test.ts
Add an upsert method to devices api
=> feat: upsert devices

lib/modules/model/types/ModelApi.ts
This adds the common search parameters to the request types for the newly added search model actions.
=> feat: improve search model request types

lib/modules/device/DeviceService.ts
This PR adds the logic necessary to replace `undefined` metadata with the default one defined in the device model.
- Step 1 : Create or choose a device model with default metadata
- Step 2 : Create one device from this model without defining metadata
- Step 3 : Get the device and check if the metadata gets the default values
=> fix(device): device creation apply default metadata 

doc/2/controllers/assets/ingest-measure/index.md, doc/2/controllers/assets/ingest-measures/index.md
Adds since badges to ingestMeasure(s) methods
=> docs: add since badges to ingestMeasure(s) method

lib/modules/measure/MeasureService.ts, tests/scenario/modules/ingestion-pipeline/pipeline-process-before.test.ts
Branch pointing to 2-dev of #387
=> fix: last measured at

CHANGELOG.md, lib/modules/asset/AssetService.ts, lib/modules/device/DeviceService.ts, package-lock.json, package.json, tests/scenario/modules/assets/asset-migrate-tenant.test.ts, types/package.json
- Step 1 :
- Step 2 :
- Step 3 :
=> release(backport): backport 2.7.1 & 2.7.2 on beta branch

doc/2/controllers/assets/updateModelLocales/index.md, lib/modules/asset/AssetService.ts
Manage a proper error message when an asset model is not found and update documentation
- Step 1 :
- Step 2 :
- Step 3 :
=> fix: manager error when asset model is not found
