doc/1/guides/provisioning/index.md
features/Provisionning.feature
features/support/hooks.js
lib/DeviceManagerPlugin.ts
lib/core-classes/PayloadService.ts

This PR change the `autoProvisioning` property and standardize it with the existing catalog one.

typo & add type: auto for provisioning

---

doc/1/controllers/device/import-devices/index.md
features/DeviceController.feature
lib/controllers/DeviceController.ts
lib/core-classes/DeviceService.ts

This PR allow the developer to import device within the app using the CSV format
Import devices from a CSV file
---
```http
URL: http://kuzzle:7512/_/device-manager/devices/_import[?refresh=wait_for]
Method: POST
```
```js
{
"controller": "device-manager/device",
"action": "importDevices",
"body": {
"csv": "qos.battery,measures.temperature.degree\\n80,23.3"
}
}
```
```bash
kourou device-manager/device:importDevices --body '{ "csv": "qos.battery,measures.temperature.degree\\n80,23.3" }'
```
---
- `csv`: a csv syntax compatible containing at least this two headers `tenantId,deviceId` with their corresponding values
- `refresh`: if set to `wait_for`, Kuzzle will not respond until the documents are indexed
---
```js
{
"status": 200,
"error": null,
"index": "<index>",
"controller": …
```

Allow the developper to import devices using csv a compatible syntax

---

doc/1/guides/assets/index.md
features/fixtures/application/app.ts
lib/core-classes/PayloadService.ts
package-lock.json
package.json

Rename the event `tenant:<tenant-id>:asset:measures:new` to `engine:<tenant-id>:asset:measures:new`
You should replace usage of event `tenant:<tenant-id>:asset:measures:new` by `engine:<tenant-id>:asset:measures:new`
```
// before
app.pipe.register('tenant:tenant-kuzzle:asset:measures:new', async () => {
// ...
});
// after
app.pipe.register('engine:tenant-kuzzle:asset:measures:new', async () => {
// ...
});
```

[breaking] Rename tenant event to engine event

---

doc/1/controllers/asset/update/index.md
features/AssetController.feature
features/fixtures/application/app.ts
lib/controllers/AssetController.ts
lib/controllers/CRUDController.ts

Two events are triggered by this action, that can be used as follow:
```js
app.pipe.register('device-manager:asset:update:before', async ({ asset, updates }) => {
app.log.debug('before asset update triggered');
set(updates, 'metadata.enrichedByBeforeAssetUpdate', true);
return { asset, updates };
})
app.pipe.register('device-manager:asset:update:after', async ({ asset, updates }) => {
app.log.debug('after asset update triggered');
if (updates.metadata.enrichedByBeforeAssetUpdate) {
set(updates, 'metadata.enrichedByAfterAssetUpdate', true);
await app.sdk.document.update(
updates.metadata.index,
'assets',
asset._id,
updates,
)
}
return { asset, updates };
})
```

[events] Add before/after events on asset:update

---

doc/1/guides/provisioning/index.md
features/Provisionning.feature
features/fixtures/application/app.ts
lib/core-classes/DeviceManagerEngine.ts
lib/core-classes/DeviceService.ts
lib/core-classes/PayloadService.ts
package-lock.json

Two events when the provisioning happen, allowing to modify the device/admin catalog and/or the tenant catalog before and after it is provisioned:
```js
app.pipe.register('device-manager:device:provisioning:before', async ({ device, adminCatalog, tenantCatalog }) => {
app.log.debug('before provisioning trigered');
set(device, '_source.metadata.enrichedByBeforeProvisioning', true);
return { device, adminCatalog, tenantCatalog };
})
app.pipe.register('device-manager:device:provisioning:after', async ({ device, adminCatalog, tenantCatalog }) => {
app.log.debug('after provisioning trigered');
return { device, adminCatalog, tenantCatalog };
})
```

add provisioning event before and after

---

doc/1/controllers/device/attach-tenant/index.md
doc/1/controllers/device/m-attach-tenants/index.md
features/DeviceController.feature
features/fixtures/application/app.ts
lib/core-classes/DeviceService.ts

Two events when this action is called, allowing to modify the device before it is attached to tenant:
```js
app.pipe.register('device-manager:device:attach-tenant:before', async ({ index, device }) => {
app.log.debug('before attach-tenant trigered');
set(device, 'body.metadata.enrichedByBeforeAttachTenant', true);
return { index, device };
})
app.pipe.register('device-manager:device:attach-tenant:after', async ({ index, device }) => {
app.log.debug('after attach-tenant trigered');
return { index, device };
})
```

event before after attachtenant

---

lib/core-classes/DeviceService.ts
package-lock.json
package.json

The entire `options` object was given to `mCreate` and `mUpdate` methods and it could contains `_id` or other arguments than were also passed to Kuzzle

Fix passing options containing potential ID

---

features/DeviceController.feature
lib/core-classes/DeviceService.ts

When unlinking an asset, the device measure was kept in the asset document

Remove measure when unlinking asset

---

features/AssetController.feature
features/DeviceController/LinkAsset.feature
features/DeviceController/UnlinkAsset.feature
features/PayloadController.feature
features/fixtures/fixtures.js
features/support/hooks.js
lib/controllers/AssetController.ts
lib/core-classes/AssetService.ts
lib/core-classes/Decoder.ts
lib/core-classes/PayloadService.ts
lib/mappings/measuresMappings.ts
lib/measures/MovementMeasure.ts
lib/types/DecodedPayload.ts
lib/types/measures/MeasureContent.ts

When a measure is made, the device may be linked to an asset. We might want to find an asset measure history across many devices so we need to keep a property containing the `assetId`.
This PR save the `assetId` in the measure document and expose a new API action to retrieve measures history for an asset: `device-manager/asset:measures`

Add API action te retrieve measures linked to an asset

---

features/DeviceController/LinkAsset.feature
features/DeviceController/MultipleLink.feature
features/DeviceController/UnlinkAsset.feature
features/fixtures/fixtures.js
features/support/assertions.js
lib/controllers/AssetController.ts
lib/controllers/DeviceController.ts
lib/core-classes/AssetService.ts
lib/core-classes/DeviceService.ts
lib/core-classes/PayloadService.ts
lib/mappings/assetsMappings.ts
lib/mappings/deviceMappings.ts
lib/types/BaseAssetContent.ts
lib/types/DeviceContent.ts
lib/types/measures/MeasureDefinition.ts

Add name to measures from devices in asset to attach multiple devices with same measures name in one asset.
- Create engine, one asset and two devices.
- attach one device to the asset 
- attach the other device with  "measuresNames" in the body
- send payload from the two devices. 
- check the asset state.
correct the "content match" step for tables.

measures name in link between assets and devices

---

doc/2/controllers/asset-category/create/index.md
doc/2/controllers/asset-category/delete/index.md
doc/2/controllers/asset-category/get/index.md
doc/2/controllers/asset-category/index.md
doc/2/controllers/asset-category/linkMetadata/index.md
doc/2/controllers/asset-category/linkParent/index.md
doc/2/controllers/asset-category/unlinkMetadata/index.md
doc/2/controllers/asset-category/unlinkParent/index.md
doc/2/controllers/asset-category/update/index.md
doc/2/controllers/metadata/create/index.md
doc/2/controllers/metadata/delete/index.md
doc/2/controllers/metadata/index.md
doc/2/controllers/metadata/update/index.md
features/AssetCategory.feature
lib/controllers/AssetCategoryController.ts
lib/controllers/AssetController.ts
lib/controllers/RelationalController.ts
lib/core-classes/AssetCategoryService.ts
lib/mappings/assetCategoryMappings.ts
lib/mappings/assetsMappings.ts
lib/types/AssetCategoryContent.ts

- Create basic documentation for metadata and assetCategory controllers
- add geopoint type and enum type in metadata (and functionnal tests)
- correct some minor mistakes
You can use Functionnal tests, or call different function of metadata, assetCategory and asset controllers with postman to create asset category and assets using the new metadata types.

add new metadata types, and correct some minor error

---

lib/core-classes/AssetCategoryService.ts
lib/core-classes/registers/MeasuresRegister.ts
package-lock.json
package.json

Allows this
```
const m = new MeasuresRegister();
m.register('temperature1', {
unit: {
name: '',
sign: '',
type: ''
},
valuesMappings: { temperature: { type: 'keyword' } }
});
m.register('temperature2', {
unit: {
name: '',
sign: '',
type: ''
},
valuesMappings: { temperature: { type: 'keyword' } }
});
```

2.0.0-rc8 : Allows to register measure with a value of same mappings

---

features/DeviceController/LinkAsset.feature
features/PayloadController.feature
features/fixtures/application/testPipes.ts
lib/DeviceManagerPlugin.ts
lib/core-classes/Decoder.ts
lib/core-classes/MeasureService.ts
lib/core-classes/PayloadService.ts
lib/models/BaseAsset.ts
lib/models/Device.ts
lib/types/DecodedPayload.ts
lib/types/measures/MeasureContent.ts
package-lock.json
package.json

Add a new event to enrich measures with data coming from the linked asset: `device-manager:measures:receive`
The `MeasureService` has been refactored to allow that. Before, caches were built to group requests but it was forbidding from triggering individual events per device.
The performance hit (if any) should be negligible since we are batching requests anyway. If needed, we will fine tune performances later.

Allow to enrich measure with asset info

---

features/PayloadController.feature
lib/mappings/measuresMappings.ts

The usage of `nested` is only useful when dealing with array of objects

Remove nested `origin` property from measure

---

doc/1/controllers/decoder/list-decoders/index.md
features/Decoders.feature
features/DeviceController/Misc.feature
features/fixtures/application/app.ts
features/fixtures/application/decoders/DummyMultiTempDecoder.ts
features/fixtures/application/decoders/DummyTempDecoder.ts
features/fixtures/application/decoders/DummyTempPositionDecoder.ts
lib/DeviceManagerPlugin.ts
lib/controllers/AssetController.ts
lib/controllers/DecoderController.ts
lib/controllers/DeviceController.ts
lib/controllers/index.ts
lib/core-classes/AssetService.ts
lib/core-classes/Decoder.ts
lib/core-classes/DeviceService.ts
lib/core-classes/MeasureService.ts
lib/core-classes/PayloadService.ts
lib/core-classes/registers/DecodersRegister.ts
lib/measures/BatteryMeasure.ts
lib/measures/HumidityMeasure.ts
lib/measures/MovementMeasure.ts
lib/measures/PositionMeasure.ts
lib/measures/TemperatureMeasure.ts
lib/models/BaseAsset.ts
lib/types/DecodedPayload.ts
lib/types/DecoderContent.ts
lib/types/index.ts
lib/types/measures/MeasureContent.ts
lib/types/measures/MeasureDefinition.ts

This PR implements the following DX changes for the Decoder class:
- The constructor does not take any arguments
- The device model is inferred from the class name (e.g. `AbeewayGPSDecoder` => device model name is `AbeewayGPS`) or use the `deviceModel` property
- Measures declaration is done in the `measures` property as an array of objects containing a `name` and `type` properties
- `DecodedPayload` is now a class with a `addMeasurement` method and should be returned from the `Decoder.decode` method
Full example:
```js
class DummyTempDecoder extends Decoder {
constructor () {
super();
this.measures = [
{ name: 'mainBattery', type: 'battery' },
{ name: 'temperature', type: 'temperature' },
];
this.payloadsMappings = {
deviceEUI: { type: 'keyword' }
};
}
async decode (payload: JSONObject): …
```

Improve DX for Decoder class

---

features/AssetCategory.feature
lib/controllers/AssetController.ts
lib/controllers/RelationalController.ts
lib/core-classes/AssetCategoryService.ts
lib/core-classes/DeviceService.ts

add custom search endpoint for assets, giving preprocessed assets
Do POST http request on http://{{kuzzle}}:7512/_/device-manager/{{engineId}}/assets/_search
part of code of assetController go to assetService to have a lighter controller.

Create a custom search endpoint for assets

---

features/fixtures/application/app.ts
features/fixtures/application/decoders/DummyAccelerometer3d.ts
features/fixtures/application/decoders/index.ts
features/fixtures/application/measures/Acceleration3dMeasure.ts
lib/core-classes/MeasureService.ts

Implement the example of `MeasureDefinition` and `Decoder` of the guides in the functional test application.
Follow the new guide :)

Add code from the guide in the functional test application

---

features/AssetController.feature
lib/controllers/AssetController.ts
package-lock.json
package.json

fix(AssetController): pass options to search query

---

features/AssetController.feature
features/DeviceController/LinkAsset.feature
features/PayloadController.feature
features/fixtures/application/testPipes.ts
lib/DeviceManagerPlugin.ts
lib/core-classes/MeasureService.ts
lib/mappings/measuresMappings.ts
lib/types/measures/MeasureContent.ts

- asset metadata (and other information) copy in measures
- mesuredat mapping  chganged from double to date.

asset metadata and mesuredat mapping correction

---

lib/modules/asset-category/AssetCategoryService.ts

When send metadata "geolocation" with `geo_point` like:
```json
{
"geolocation": {
"lat": 0,
"lon": 0
}
}
```
The data are formated in object
```json
{
"key": "geolocation",
"value": {
"object": [
{
"key": "lat",
"value": {
"integer": 0
}
},
{
"key": "lon",
"value": {
"integer": 0
}
}
]
}
}
```
Instead of geo_point like
```json
{
"key": "geolocation",
"value": {
"geo_point": {
"lat": 0,
"lon": 0
}
}
}
```
It's due to this test:
https://github.com/kuzzleio/kuzzle-device-manager/blob/26d87060eb5a8855737a40f7e78582928b08802b/lib/modules/asset-category/AssetCategoryService.ts#L205
It's not "safe" because value `0` are considered like `falsy` so in this case format in geo_point are ignored and pass in the next condition "format like object" and produce bad metadata.
So In this case prefer test …

correct format geo_point

---

features/Decoder/PayloadController.feature
features/fixtures/application/decoders/DummyTempDecoder.ts
lib/modules/decoder/DecodedPayload.ts

Ensure the `measuredAt` timestamp is an Unix Timestamp (milliseconds)

Ensure unix timestamp for measuredAt

---

lib/core/registers/DecodersRegister.ts

Do not try to create permissions when no decoder are registered.

Skip permissions creation when no decoder are registered

---

features/fixtures/application/decoders/DummyTempDecoder.ts
features/fixtures/application/decoders/DummyTempPositionDecoder.ts
lib/modules/decoder/Decoder.ts
lib/modules/decoder/PayloadService.ts
package-lock.json
package.json

Instantiate the `DecoderPayload` and pass it directly to the `Decoder.decode` method.
Before
```
async decode(
payload: JSONObject,
): Promise<DecodedPayload<DummyTempDecoder>> {
const decodedPayload = new DecodedPayload<DummyTempDecoder>(this);
// decode measurements..
return decodedPayload;
}
```
After
```
async decode(
decodedPayload: DecodedPayload<DummyTempDecoder>,
payload: JSONObject,
): Promise<DecodedPayload<DummyTempDecoder>> {
// decode measurements..
return decodedPayload;
}
```

[breaking] Pass decodedPayload to Decoder.decode method

---

features/Asset/Controller.feature
features/Device/Controller/LinkAsset.feature
features/Measure/IngestionPipeline.feature
features/Model/Controller.feature
features/fixtures/application/app.ts
features/fixtures/application/testPipes.ts
features/fixtures/fixtures.js
lib/core/DeviceManagerEngine.ts
lib/core/DeviceManagerPlugin.ts
lib/core/registers/ModelsRegister.ts
lib/modules/asset/AssetService.ts
lib/modules/asset/collections/assetsMappings.ts
lib/modules/asset/types/AssetContent.ts
lib/modules/device/DeviceService.ts
lib/modules/device/DevicesController.ts
lib/modules/device/types/DeviceApi.ts
lib/modules/measure/MeasureService.ts
lib/modules/measure/types/MeasureEvents.ts
lib/modules/model/ModelService.ts
lib/modules/model/ModelsController.ts
lib/modules/model/collections/modelsMappings.ts
lib/modules/model/types/ModelApi.ts
lib/modules/model/types/ModelContent.ts
lib/modules/model/types/ModelDefinition.ts
package-lock.json
package.json
types/package.json

Change `device-manager/devices:linkAsset` API action. The new format is specified in the type `ApiDeviceLinkAssetRequest`. The `measures` is not a table anymore but an array which each element describe a measure with it's `name` and `type` to avoid confusion between key/value.
```
action: "linkAsset";
_id: string;
refresh?: string;
assetId: string;
body?: {
/**
* Names of the linked measures
*
* Array<{ asset: string, device: string }>
*
* @example
*
* [
*   { asset: "externalTemperature", device: "temperature" }
* ]
*/
measureNames: Array<{ asset: string; device: string }>;
};
```
The method to register default devices and array also changed accordingly (`Plugin.registerAsset` and `Plugin.registerDevice`).
The `assets` collection changed as well. `measures` become `measureNames` and have …

[breaking] Change the `measures` property in API and data model to be more intuitive

---

features/Asset/Controller.feature
features/fixtures/application/app.ts
features/fixtures/application/assets/Container.ts
features/fixtures/application/assets/Warehouse.ts
lib/modules/asset/AssetService.ts
lib/modules/asset/AssetsController.ts
lib/modules/asset/types/AssetApi.ts
package.json
types/package.json

This PR allows to pass a search query and a sort to the `device-manager/assets:getMeasures` action.
- add a `type` to filter on measure types
- add the `total` number of measures

Allow search query when retrieving asset measures

---

features/Asset/Controller.feature
features/fixtures/application/app.ts
features/fixtures/application/tests/controller.ts
features/fixtures/application/tests/pipes.ts
lib/modules/asset/AssetService.ts
lib/modules/device/DeviceService.ts

Every modification of a Digital Twin (Asset or Device) through associated controllers is contextualized with the user who made the request to keep a trace in Kuzzle metadata.
This allows for example to know who has modified a metadata or link a new device to an asset by consulting history documents in `assets-history` collection.
When a request is made to those controllers from the backend, there is no user since it's the EmbeddedSDK executing the request and it was causing an error.
This PR fix that, when the EmbeddedSDK is used to execute one of those action, it will use the user if the sdk was contextualized with [sdk.as](https://docs.kuzzle.io/core/2/guides/develop-on-kuzzle/embedded-sdk/#user-impersonation) method, otherwise the metadata will be set with the `null` user ID who …

Fix Asset and Device creation from backend

---

features/Device/Controller/LinkAsset.feature
features/fixtures/fixtures.js
lib/modules/device/DeviceService.ts
lib/modules/device/DevicesController.ts
lib/modules/device/types/DeviceApi.ts
package-lock.json
package.json

Add the `implicitMeasuresLinking` option to `device-manager/devices:linkAsset` action.
This option allows to not specify the names of all the measures that should be linked to the asset. The algorithm will go through all the measures names provided by the device and add the one who are present with the same name in the asset. 
It will not add the measure if:
- it has been specified in the link request
- it was already present in the asset

Allows to implicitly link asset to device without specifying every measure names

---

features/fixtures/application/assets/Container.ts
features/fixtures/application/tests/pipes.ts
features/fixtures/fixtures.js
lib/modules/measure/MeasureService.ts
lib/modules/measure/types/MeasureContent.ts
lib/modules/shared/index.ts
lib/modules/shared/utils/objectDiff.ts
tests/helpers/payloads.ts
tests/modules/assets/asset-history.test.ts

When an asset receive a measure, we also check if a metadata was updated in the ingestion pipeline. If it's the case then it appear in the `event` property:
```js
"asset": { /* asset content */ },
"event": {
"measure": {
"names": [
"temperatureExt"
]
},
"name": "measure",   // history document from a new mesure
"metadata": {              // but a metadata was also changed in the ingestion pipeline
"names": [
"weight",                 // simple metadata, was supported
"trailer.capacity"    // nested metadata, supported now
]
}
},
"id": "Container-linked1"
```

Support nested metadata diff for asset history

---

features/fixtures/application/tests/pipes.ts
lib/core/DeviceManagerEngine.ts
lib/modules/measure/MeasureService.ts
lib/modules/measure/collections/getEmbeddedMeasureMappings.ts
lib/modules/measure/index.ts
lib/modules/shared/types/EmbeddedMeasure.ts
package-lock.json
package.json
tests/modules/devices/action-receive-measure.test.ts

Add the `originId` property to `EmbeddedMeasure` which contains the Device ID when the measure comes from a Device.
It's more easier to retrieve the device who sent the measure, otherwise developers needs to find the device ID in the `linkedDevices` array from the measure name.

Add `originId` digital twins embedded measures

---

doc/2/controllers/devices/linkAsset/index.md

- Step 1 : clone and run a backend
- Step 2 : try to link a device to a payload using the _link in the query string

Fix action name link => _link

---

doc/2/concepts/measures-ingestion/index.md
lib/modules/decoder/DecodingState.ts
lib/modules/decoder/PayloadService.ts
lib/modules/decoder/SkipError.ts
lib/modules/decoder/StateDecoder.ts
lib/modules/decoder/collections/payloadsMappings.ts
tests/scenario/migrated/decoder-payload-controller.test.ts

- Store if a payload is skipped, valid or error.
- Store the reason of the error, when a user defined validation error occurs.

Store reason of discarded payloads

---

lib/modules/model/ModelService.ts
tests/scenario/migrated/model-controller.test.ts
tests/scenario/modules/models/model-controller.test.ts

This PR changes the `document.upsert` calls in `ModelService` into `document.createOrReplace` calls, in order to match the behavior described in the documentation.
It also updates the related tests.

ModelService upsert -> createOrReplace

---

lib/modules/asset/AssetService.ts
lib/modules/asset/types/AssetHistoryContent.ts
tests/scenario/modules/assets/asset-history.test.ts

- When an asset is created or updated, we saved the complete paths in asset history document.
Closes #276

Full path nested metadata when create/update assets

---

.eslintrc.json
jest.config.ts
package-lock.json
package.json
tests/scenario/modules/devices/action-receive-measure.test.ts
tests/scenario/modules/devices/action-scrud.test.ts
tests/scenario/modules/ingestion-pipeline/propagation.test.ts
tests/tsconfig.json
tsconfig.json

This PR splits the Typescript config in order to avoid emitting test scenarios in production code.
It also adds linting to the tests.

Split tsconfig for tests

---

lib/modules/asset/AssetService.ts
lib/modules/asset/types/AssetEvents.ts
lib/modules/model/ModelService.ts
lib/modules/plugin/DeviceManagerEngine.ts
package-lock.json
package.json
tests/scenario/modules/models/asset-model-metadata-propagation.test.ts

This PR implements the propagation of any metadata addition / deletion on an asset model to the linked assets.
Fixes #277

Update metadata in existing assets when the model is modified

---

lib/modules/shared/types/Metadata.ts

Allow to specify nested metadata
Example:
```js
metadata: {
geofence: {
name: 'Amazon Saran',
group: 'warehouse',
polygon: [
// array of coordinates
],
disabled: false,
},
},
```

Allow JSONObject in metadata

---

lib/modules/asset/collections/assetsHistoryMappings.ts
lib/modules/asset/collections/assetsMappings.ts
lib/modules/asset/exports.ts
lib/modules/device/collections/deviceMappings.ts
lib/modules/device/exports.ts
lib/modules/measure/collections/measuresMappings.ts
lib/modules/measure/exports.ts
lib/modules/model/collections/modelsMappings.ts

Export the base mappings for the plugin collection.
This can be used to define other collection based on KDM collections.
Example usage https://github.com/kuzzleio/kuzzle-iot-backend/pull/18

Export default mappings

---

doc/2/concepts/measures-ingestion/index.md
lib/modules/measure/MeasureService.ts
lib/modules/measure/types/MeasureEvents.ts
package-lock.json
package.json
tests/application/tests/pipes.ts
tests/scenario/modules/ingestion-pipeline/pipeline-persist-before.test.ts
tests/scenario/modules/ingestion-pipeline/pipeline-process-before.test.ts

Add a new event triggered after measure have been updated in asset and device but before persistence.
This allow to modify the final state of the asset/device before saving them.
Needed for https://github.com/kuzzleio/kuzzle-iot-backend/pull/19

Add `persist:before` event to the ingestion pipeline

---

lib/modules/measure/MeasureExporter.ts
tests/scenario/modules/assets/action-export-measures.test.ts
tests/scenario/modules/devices/action-export-measures.test.ts

This PR fixes empty values when measure named differed from measure types.
Previously, when you had a measure named `temperatureExt` of type `temperature`, it tried to get the value with the current path : `values.temperatureExt` where it should have been `values.temperature`.
Plus, this allows us to use custom header names instead of the paths to the value.

fix: CSV column headers and path to values should not be the same

---

lib/modules/measure/MeasureExporter.ts
tests/scenario/modules/assets/action-export-measures.test.ts
tests/scenario/modules/devices/action-export-measures.test.ts

While exporting asset measures as csv, for each measure payload, checks if the current asset's measure has the right `measureName`.
This allows us to export the measures of an asset with multiple measure of the same type, but different names, correctly.
* Changed csv headers

fix(csv export): asset with measures of the same type but different names

---

doc/2/controllers/assets/get-measures/index.md
doc/2/controllers/models/get-asset/index.md
doc/2/controllers/models/get-device/index.md
doc/2/controllers/models/get-measure/index.md

Fixes incorrect arguments in the request to retrieve a device's model.

fix(docs): wrong arguments in models' getDevice request

---

lib/modules/asset/collections/assetsMappings.ts
lib/modules/decoder/PayloadService.ts
lib/modules/device/DeviceService.ts
lib/modules/device/collections/deviceMappings.ts
lib/modules/measure/MeasureService.ts
lib/modules/shared/types/DigitalTwinContent.ts
tests/application/decoders/DummyTempDecoder.ts
tests/application/decoders/DummyTempPositionDecoder.ts
tests/helpers/payloads.ts
tests/scenario/modules/ingestion-pipeline/pipeline-persist-before.test.ts
tests/scenario/modules/ingestion-pipeline/pipeline-process-before.test.ts

Just add the property `lastMeasuredAt` on DigitalTwin (assets/devices), that save the date of last received measure.
- Step 1 : Start dev server
- Step 2 : Send payload
- Step 3 : Observe the property `lastMeasuredAt` has been updated with more recent `measuredAt` of payloads 
Add format measure value with `measuredAt` like `{ value: <myValue>, measuredAt: <timestamp> }` and method `isMeasureDated` to differentiate the format.
This new format is useful for functional tests, to test the payloads with multiple dates.

feat(measures): add lastMeasuredAt on DigitalTwin

---

.gitignore
lib/modules/asset/AssetsController.ts
lib/modules/asset/types/AssetApi.ts
lib/modules/device/DevicesController.ts
lib/modules/device/types/DeviceApi.ts
lib/modules/measure/MeasureExporter.ts
lib/modules/shared/index.ts
lib/modules/shared/services/AbstractExporter.ts
lib/modules/shared/services/DigitalTwinExporter.ts
lib/modules/shared/services/index.ts
package-lock.json
package.json
tests/fixtures/fixtures.ts
tests/scenario/modules/assets/action-export-measures.test.ts
tests/scenario/modules/assets/action-export.test.ts
tests/scenario/modules/devices/action-export-measures.test.ts
tests/scenario/modules/devices/action-export.test.ts

Add the list exports for digitalTwins
- Step 1 : Call in `POST` the endpoint `/device-manager/<engineId>/<type>/_export`, with `query` and `sort` in body
- Step 2 : Call the URL returned by previous request, you should get a CSV file
`<type>` is `assets` or `devices`
Refactor `MeasureExporter` with `AbstractExporter` to mutualize the exports logic

feat: digitaltwin exports

---

lib/modules/asset/AssetHistoryService.ts
lib/modules/asset/AssetService.ts
lib/modules/decoder/PayloadService.ts
lib/modules/device/DeviceService.ts
lib/modules/measure/MeasureService.ts
lib/modules/model/ModelService.ts
lib/modules/shared/services/BaseService.ts
lib/modules/shared/services/index.ts
tests/scenario/modules/devices/action-export-measures.test.ts

Refactor services to use the abstract shared class `BaseService`.
This abstract class provide some useful getters like `sdk`, `impersonatedSdk`, `config`.
Also to future, this allows to provide easily other getters or methods shared between services.

refactor: add BaseService

---

lib/modules/asset/model/AssetSerializer.ts
lib/modules/asset/types/AssetContent.ts
lib/modules/measure/collections/measuresMappings.ts
tests/application/tests/pipes.ts

Currently, in the asset part of the measure, we do not store the groups of the asset.
We add it, so we will be able to use it in dashboards/widgets.
E.G , we want to display the temperature of the assets inside a specific group.

Add groupsAsset in measures. Update measures mapping accordingly

---

lib/modules/asset/AssetService.ts
lib/modules/asset/AssetsController.ts
lib/modules/device/DeviceService.ts
lib/modules/device/DevicesController.ts
lib/modules/plugin/exports.ts
lib/modules/plugin/index.ts
lib/modules/plugin/types/Pipes.ts
lib/modules/plugin/types/exports.ts
lib/modules/plugin/types/index.ts
lib/modules/shared/services/BaseService.ts

Use `BaseService` implemented in #319 to implement sdk methods wrapper to trigger [generic:document](https://docs.kuzzle.io/core/2/framework/events/generic-document) events for internal SCRUD calls for Assets and Devices
Todo add to documentation the events `generic:document:beforeSearch` and `generic:document:afterSearch` which was not yet defined.

feat(digitalTwin): implement generic document pipes triggers

---

jest.config.ts
lib/modules/device/collections/deviceMappings.ts
lib/modules/plugin/DeviceManagerEngine.ts
lib/modules/plugin/DeviceManagerPlugin.ts
lib/modules/plugin/types/DeviceManagerConfiguration.ts
tests/application/app.ts
tests/scenario/custom-mapping.test.ts
tests/scenario/modules/devices/action-export-measures.test.ts

Allow to modify digital twin mapping from application.
These allow to extend mapping properties from application to use custom properties in documents.
This is needed to add `softTenant` property to restrict access to a specific soft tenant, this mapping modification is added from package iot-platform-backend package with plugins setup.

feat(digitalTwin): allow to modify mapping from application

---

doc/2/controllers/assets/upsert/index.md
lib/modules/asset/AssetService.ts
lib/modules/asset/AssetsController.ts
lib/modules/asset/types/AssetApi.ts
lib/modules/plugin/DeviceManagerPlugin.ts
lib/modules/shared/services/BaseService.ts
tests/scenario/migrated/asset-controller.test.ts

This PR adds an upsert method in the AssetService. The upsert method is designed to update an existing asset with new metadata, or create a new asset if one does not already exist with the specified assetId.
npm run test:functional

Kzlprd 166 upsert assets

---

lib/modules/asset/AssetsGroupsController.ts
tests/fixtures/rights.ts
tests/scenario/modules/assets/asset-group-permissions.test.ts

Disable useless `checkRights` on impersonate in `AssetsGroupsController`.
That cause useless checks and request the rights on the document controller despite user have permission for `device-manager/assetsGroup` routes
Add tests with user with restricted permissions to tests permissions are correctly applied

fix(assetsGroups): disable checkRights on impersonate

---

lib/modules/measure/MeasureExporter.ts
tests/scenario/modules/assets/action-export-measures.test.ts
tests/scenario/modules/devices/action-export-measures.test.ts

- fix measures export when we have multiple values in a measure
- handle multiple measures of same type diferently
- use full type + full path as header

Fix csv measures exporter

---

lib/modules/asset/AssetService.ts
tests/scenario/modules/assets/asset-migrate-tenant.test.ts

Raise an error if all assets to migrate tenants already exists in tenant destination

Fix(migrate_tenant_sanity_check) : raise an error

---

doc/2/controllers/models/write-asset/index.md
doc/2/controllers/models/write-device/index.md
lib/modules/model/types/ModelContent.ts
lib/modules/model/types/ModelDefinition.ts
tests/application/assets/Container.ts
tests/scenario/migrated/model-controller.test.ts

add group descriptions to models

feat: add group descriptions to models

---

.github/workflows/push_branches.workflow.yaml
.releaserc.js
.releaserc.json
releaseTypes.mjs
types/package.json
types/scripts/copy-version.js

Create `semantic-release` plugin to release the type package instead of having to do it manually.
Also improve type package release delivery by handle beta release tag (not handled actually), that avoid to use `latest` tag when release a beta.

build(types): use semantic-release for types package

---

lib/modules/model/types/ModelContent.ts

Simply add support nested metadata object, for below example, currently the `level2` can't have a `properties` field for nested object, the new type defines circular for `MetadataObject` to support it.
```ts
export const SampleDeviceDefinition: DeviceModelDefinition = {
decoder: new SampleDeviceDecoder(),
defaultMetadata: {},
metadataMappings: {
level1: {
properties: {
level2: {
properties: {
level3: { type: 'text' },
},
},
},
},
},
};
```

feat(metadata): add support nested metadata object

---

doc/2/controllers/assets/replace-metadata/index.md
lib/modules/asset/AssetService.ts
lib/modules/asset/AssetsController.ts
lib/modules/asset/types/AssetApi.ts
lib/modules/model/types/ModelContent.ts

It will add two fields ('strategy' et 'format') in MetadataProperty to allow geoshape circle and date format according to ES documentation.
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/geo-shape.html#_circle
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/mapping-date-format.html
It implements a replace metadata endpoint for an asset. The issue was some fields cannot be removed when using basic update metadata endpoint. Some ES type needs strict typing like geo_shape polygon and it sends an error if there is additional field (basic updating polygon over circle is wrongly keeping radius field).
Types tests can pass successfully instead of putting typescript ignores.
'format' field included to store an already formatted date …

Kzlprd 323 asset metadata

---

doc/2/controllers/assets/delete/index.md
doc/2/controllers/devices/delete/index.md
lib/modules/device/DevicesController.ts
package.json
tsconfig.test.json

Simply correct HTTP API for device controller, according to documentation, and homogenize compared to assets API.
Update device should use `POST:/_/device-manager/<tenantId>/device/<useless>?_id=<deviceId>`
Delete device should use `DELETE:/_/device-manager/<tenantId>/device/<useless>?_id=<deviceId>`
Update device should use `PUT:/_/device-manager/<tenantId>/devices/<deviceId>`
Delete device should use `DELETE:/_/device-manager/<tenantId>/devices/<deviceId>`

fix(device): correct device HTTP API

---

doc/2/concepts/configuration/index.md
docker-compose.yml
lib/modules/plugin/DeviceManagerEngine.ts
lib/modules/plugin/DeviceManagerPlugin.ts
lib/modules/plugin/types/DeviceManagerConfiguration.ts

It add missing `settings` fields in the plugin configuration and make sure to use it during indices creation
Using the kuzzlerc file, you can now set the desired index settings. For example the following configuration:
```js
{
"plugins": {
"device-manager": {
"engineCollections": {
"config": {
"settings": {
"number_of_shards": 3
}
},
"asset": {
"settings": {
"number_of_shards": 4
}
},
"assetGroup": {
"settings": {
"number_of_shards": 1
}
},
"assetHistory": {
"settings": {
"number_of_shards": 3
}
},
"device": {
"settings": {
"number_of_shards": 2
}
},
"measures": {
"settings": {
"number_of_shards": 7
}
}
}
}
}
}
```
gives you the following index configuration when you create a tenant:
Add a complete documentation about the plugin configuration usage

feat(configuration): allow to specify Elasticsearch index settings

---

lib/modules/measure/MeasureService.ts
lib/modules/measure/collections/measuresMappings.ts
lib/modules/measure/types/MeasureContent.ts
lib/modules/plugin/DeviceManagerEngine.ts
tests/scenario/migrated/measure-ingestion-pipeline.test.ts

This PR add a step to the measure ingestion pipeline, the goal is to add the origin device metadata to the measure origin
- Step 1 : Create a device with metadata
- Step 2 : Push a payload through it
- Step 3 : Check the measure document origin
Conflict would not update for `commons` group
Return conflicts only when there is at least one

feat(measure): add device metadata to origin

---

doc/1/guides/assets/index.md
doc/2/concepts/digital-twins-devices-assets/index.md
lib/modules/asset/types/AssetHistoryContent.ts
lib/modules/measure/MeasureService.ts
tests/scenario/migrated/asset-history.test.ts
tests/scenario/migrated/decoder-payload-controller.test.ts
tests/scenario/modules/assets/asset-history.test.ts

This removes writes to the `asset-history` collection when a new measure comes in. An history entry might still be created when receiving a measure if the measure updates the asset metadata.
Part of [KZLPRD-438](https://kuzzle.atlassian.net/browse/KZLPRD-438).
- Edited test files were clean up a little
- Fixed flaky tests that were writing to the `person` metadata in `Container` assets, which didn't contain such metadata in its metadata mappings
[KZLPRD-438]: https://kuzzle.atlassian.net/browse/KZLPRD-438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: remove asset historization when receiving a measure

---

doc/2/controllers/models/search-assets/index.md
doc/2/controllers/models/search-devices/index.md
doc/2/controllers/models/search-measures/index.md
lib/modules/model/ModelService.ts
lib/modules/model/ModelsController.ts
lib/modules/model/types/ModelApi.ts
tests/hooks/collections.ts
tests/scenario/modules/models/asset-model.test.ts
tests/scenario/modules/models/device-model.test.ts
tests/scenario/modules/models/measures-model.test.ts

This adds three actions on the `device-manager/models` controller to search for asset, device and measure models using the Elasticsearch query DSL.

feat: add search actions for the models

---

lib/modules/model/ModelService.ts
tests/application/app.ts
tests/application/assets/Room.ts
tests/application/assets/StreetLamp.ts
tests/application/measures/BrightnessMeasure.ts
tests/application/measures/CO2Measure.ts
tests/application/measures/IlluminanceMeasure.ts
tests/application/measures/PowerConsumptionMeasure.ts
tests/hooks/collections.ts
tests/scenario/modules/assets/action-export.test.ts
tests/scenario/modules/models/asset-model.test.ts
tests/scenario/modules/models/measures-model.test.ts

This fixes a regression introduced in #362 on the `listAssets` (and by extension, `searchAssets`) actions of the `device-manager/models` controller that wasn't correctly taking into account the requested engine group and was returning the models for every group instead.
The problematic Elasticsearch query has been fixed.
Two new asset models, `Room` and `StreetLamp`, were added in the test application, respectively to the `air_quality` and `public_lighting` engine groups.
Tests were added to avoid this regression in the future.
To avoid an inconsistent list of asset models, the asset models are now reset before each test of the `asset-model.test.ts` file.

fix: only list asset models for the requested engine group

---

lib/modules/decoder/PayloadService.ts

When a payload is sent to register a new measure for a device, the metadata of the device are replaced by those from the index platform (```PayloadService.ts```). So the fix is to retrieve from the associated tenant if it exists. 
KZLPRD-556
- Step 1 : check the metadata value registered in the device
- Step 2 : send a payload, for example :
```
{
"deviceEUI" : "ABE1",
"lat" : 48.8566,
"lon" : 2.2523,
"battery" : 40,
"externalTemperature" : 1,
"internalTemperature" : 1
// "timestamp" : 1711753200000
}
``` 
to this endpoint ```http://localhost:7512/_/device-manager/payload/abeeway``` 
- Step 3 : check again if the value didn't change

fix(device-metadata): fetch device's metadata from assigned tenant when available

---

lib/modules/measure/MeasureExporter.ts
package-lock.json
package.json

legacy import wich break apps if`Kuzzle >= 2.32` due to path change in the lib
Now `Kuzzle >= 2.32` is mandatory
Let it fixed but can be discussed

fix:  queryTranslator import

---

lib/modules/asset/AssetService.ts

Adds a triggerEvent to allow piping on `generic:document:afterWrite` as it was possible before KZLPRD-323

fix: trigger events on metadataReplace call

---

doc/2/controllers/models/update-asset/index.md
doc/2/controllers/models/write-asset/index.md
lib/modules/asset/AssetService.ts
lib/modules/asset/collections/assetsMappings.ts
lib/modules/decoder/PayloadService.ts
lib/modules/device/DeviceService.ts
lib/modules/device/collections/deviceMappings.ts
lib/modules/device/types/DeviceEvents.ts
lib/modules/model/ModelService.ts
lib/modules/shared/types/DigitalTwinContent.ts
tests/application/app.ts
tests/application/assets/Container.ts
tests/application/assets/index.ts
tests/application/decoders/DummyTempDecoder.ts
tests/application/decoders/DummyTempPositionDecoder.ts
tests/fixtures/fixtures.ts
tests/scenario/migrated/asset-controller.test.ts
tests/scenario/modules/devices/action-scrud.test.ts
tests/scenario/modules/models/asset-model-measure-slots-propagation.test.ts
tests/scenario/modules/models/asset-model.test.ts
tests/scenario/modules/models/device-model-measure-slots-propagation.test.ts

This adds a new field to the documents in the `assets` and `devices` collections, `measureSlots`, which is populated with the name and type of the measures from the asset/device model.
This field is automatically updated when the measures of an asset/device model is updated, for each asset/device of that model provisioned in the platform.
> [!IMPORTANT]  
> Existing assets and devices will _not_ automatically be updated with this new field.
> 
> The following script can be used to create this field manually in all existing assets and devices of all engines using [`kourou sdk:execute`](https://github.com/kuzzleio/kourou?tab=readme-ov-file#kourou-sdkexecute-code):
> <details><summary>Migration script</summary>
> 
> ```javascript
> // Change me if necessary
> const adminIndex = …
```

feat: embed measure slots in asset and device documents

---

lib/modules/measure/MeasureExporter.ts
lib/modules/shared/services/AbstractExporter.ts
lib/modules/shared/services/DigitalTwinExporter.ts
tests/scenario/modules/assets/action-export.test.ts
tests/scenario/modules/devices/action-export.test.ts

This modifies the digital twin exporter to use the recently introduced `ask:device-manager:${type}:get-last-measures` ask to retrieve the measures of a digital twin, instead of relying on the measures embedded in their documents.
This is in preparation for the removal of the `measures` and `lastMeasuredAt` fields in the documents of the assets and devices collections.
A new mechanism has been introduced in the abstract exporter, the export stream augmenters, that are used to modify the exporter search results right before they get written to the export stream.
Digital twin exporter tests were also updated to check the exact values of the export results, and to sort the export client-side (because sorting by measure in the request is no longer supported).
This deprecates the use of the …

feat: stop using measures from assets and devices in exporter

---

.releaserc.js
lib/modules/model/ModelService.ts
tests/scenario/modules/models/asset-model.test.ts

The bug appears when someone tries to create an asset with a model which uses an engineGroup sets to commons, resulting in an error in the frontend saying "insufficient permissions".
The problem comes from the assetCreate in KDM which calls the models:asset:get to get the model of the asset we want to create, the thing is that we don't check if in the engineId: commons, so when this is the case it result in an error being thrown saying the asset we are looking for doesn't exist
- Step 1 : cloen and run the iot platform
- Step 2 : run the fixtures
- Step 3 : modify the model container to change engineId to "commons"
- Step 4: try to create an asset of type Container

fix: getAsset should search in commons assets too

---

lib/modules/asset/AssetsGroupsController.ts
lib/modules/asset/collections/assetsGroupsMapping.ts
lib/modules/asset/types/AssetGroupContent.ts
lib/modules/asset/types/AssetGroupsApi.ts
tests/fixtures/assetsGroups.ts

It adds optional `type` in `AssetGroup` for asset group dashboard template feature
- Step 1 : include KDM in the `iot-platform`
- Step 2 : create an asset group for example with this payload
```
{
"controller": "device-manager/assetsGroup",
"action": "create",
"engineId": "tenant-sdef-sdef",
"body": {
"children": [],
"name": "test groupe 3",
"parent": null,
"type": "Batiment"
}
}
```
- Step 3 : update an asset
- Step 4 : test without `type`

Kzlprd 724 etq utilisateur jvp cr er des rapport type par soft tenants et par groupes

---

lib/modules/measure/MeasureService.ts

Just add mutex lock to asset document update in measures ingest to try to fix a conflict on update due to race condition.
This race condition could be arrived if 2 different devices are linked to the same asset and get processed at the same time.

fix(measure): add mutex to asset update to prevent race condition

---

lib/modules/asset/AssetService.ts
lib/modules/device/DeviceService.ts
tests/scenario/modules/assets/asset-migrate-tenant.test.ts

Add forgotten locks to fix race condition errors on digital twins

fix(digitalTwin): correct race condition

---

lib/modules/asset/roles/RoleAssetsGroupsAdmin.ts
lib/modules/asset/roles/RoleAssetsGroupsReader.ts

This PR adds following actions to `RoleAssetsGroupsAdmin` and `RoleAssetsGroupsReader`
``` ts
"device-manager/models": {
actions: {
listGroups: true,
getGroup: true,
},
},
```

fix(assetsGroups roles): add missing actions from group models

---

doc/2/concepts/metadatadetails/index.md

It changes the wrong indentations applied for editor hints documents and add javascript example.
- Step 1 : Open the preview of index at `/doc/2/concepts/metadatadetails/index.md`
- Step 2 : Import the index in the kuzzle documentation app and run `kuzdoc dev`
- Step 3 : Check if there no longer indentations
Highlight some info in Editor hints section and format some tags html

fix: update documentation for indentations

---

doc/2/concepts/models/index.md
doc/2/controllers/assets/updateModelLocales/index.md
lib/modules/asset/AssetService.ts
lib/modules/asset/AssetsController.ts
lib/modules/asset/collections/assetsMappings.ts
lib/modules/asset/types/AssetApi.ts
lib/modules/asset/types/AssetHistoryContent.ts
lib/modules/measure/types/MeasureDefinition.ts
lib/modules/model/ModelService.ts
lib/modules/model/ModelsController.ts
lib/modules/model/ModelsRegister.ts
lib/modules/model/collections/modelsMappings.ts
lib/modules/model/types/ModelApi.ts
lib/modules/model/types/ModelContent.ts
lib/modules/model/types/ModelDefinition.ts
lib/modules/plugin/DeviceManagerPlugin.ts
lib/modules/shared/types/DigitalTwinContent.ts
package-lock.json
package.json
tests/application/assets/Container.ts

This PR is related to the iot-platform [PR](https://github.com/kuzzleio/iot-platform/pull/420).
It add locales for asset model and implement an endpoint to update all assets related to this asset model. 
[Ticket](https://kuzzle.atlassian.net/browse/KZLPRD-689?atlOrigin=eyJpIjoiMDU0ZDE5ZmUwODdiNDlmNzllNjMwNWViMTQ0OTg5N2MiLCJwIjoiaiJ9)
- Step 1 : Add a locales in an `asset model`
- Step 2 : Create an `asset` from this `asset model`
- Step 3 : Check if the locales is in the document
- Step 4 : Update the `asset model`
- Step 5 : Send a PATCH request to the endpoint `device-manager/assets/modelLocales`
- Step 6 : Check the changing in all assets from the asset model

feat: update measure model for localization

---

lib/modules/asset/AssetModule.ts
lib/modules/asset/AssetsGroupsController.ts
lib/modules/asset/AssetsGroupsService.ts

This Pr adds an `assetsGroupsService` to handle group logic.
This allows more consistency with device and assets services and permit the use of base service methods allowing for pipes to b

feat(assetsGroups): add service to handle group logic

---

lib/modules/device/DeviceService.ts

Improve fix of race condition, use `_attachEngine` on create and upsert to prevent useless lock.

fix(device): use `_attachEngine` on create and upsert

---

doc/2/concepts/configuration/index.md
lib/modules/measure/MeasureService.ts
lib/modules/plugin/DeviceManagerPlugin.ts
lib/modules/plugin/types/DeviceManagerConfiguration.ts
tests/application/app.ts
tests/application/tests/controller.ts
tests/scenario/migrated/asset-history.test.ts
tests/scenario/migrated/decoder-payload-controller.test.ts
tests/scenario/modules/assets/asset-history.test.ts

This PR is breaking but the choice has been done to treat it as a feature.  Backward compatibility is insured by config flag if any project is impacted by this breaking (AFAWK, nobody uses it)

feat: measures should not be historized on asset

---

lib/modules/asset/AssetService.ts
lib/modules/model/ModelService.ts
lib/modules/model/ModelsController.ts
lib/modules/model/types/ModelApi.ts
lib/modules/plugin/DeviceManagerEngine.ts

This PR fix the regression on the asset creation and remove the usage of getAsset() in updateAssetModel() to minimize side effect.
- Step 1 : Create asset to check if its works
- Step 2 : Use updateAssetModel endpoint and check it works
- Step 3 :

fix: asset commons case

---

lib/modules/asset/AssetService.ts

This PR fixes the issue on the creation of asset models with the engine group 'commons'.
The model was created but the client receives a 400 error.
The issue was that after creating/updating an asset model we then fetch the assets from this model in the different engine to update them.
In case of commons engine group we must do this for every engine. If no engine is present we don't need to throw an error.
Create an asset model with common engine, check that there are no errors
Create an asset of this model in 2 different engines
Recreate the model with an additional metadata field
Check that your assets have been updated accordingly

fix(assetModels): error on create asset model with commons engine

---

.github/workflows/release.workflow.yaml

Simply add rebase on end of release process to keep linear history

ci: add rebase on end of release process

---

lib/modules/asset/AssetsController.ts

A promise was not awaited in a try catch in `AssetsController` `updateModelLocales`

fix(assetsController): await promise in try catch
